In [16]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Aim is to predict the marks of students of the test data

In [17]:
# Use the file namd 'training data' to train the model

data = pd.read_excel('Training data.xlsx')
x_train = np.array(data.iloc[:,0:8])
y_train = np.array(data.iloc[:,8]).reshape(-1,1)

# Try plotting y_train with different features
# To get an idea whether to add some features or not
# Add some features if required in x_train

# Also do label encoding for features not represented in numbers
# refer the link if not know : https://youtu.be/589nCGeWG1w?si=t2Wa7LgbUOO4RooM

def feature_changing(x_train):
  # ---------
    # Your code here
    columns_to_drop = ['sex' , 'age']
    x_train = pd.DataFrame(x_train , columns=['internet' , 'sex' , 'traveltime' , 'studytime' , 'freetime' , 'absences' , 'age' , 'iq'])
    x_train = x_train.replace({'yes':1 , 'no':0})
    x_train = x_train.replace({'M':1 , 'F':0})
  # ---------

    return np.array(x_train.iloc[:,0:8])

x_train = feature_changing(x_train)

print(x_train)

[[  0   1   2 ...   6  18 118]
 [  1   1   2 ...   7  19 107]
 [  1   1   3 ...   5  18 108]
 ...
 [  1   1   2 ...   5  17 123]
 [  1   0   1 ...   8  17 104]
 [  1   1   1 ...   6  18 128]]


In [18]:
def z_score(x_train):

  # ---------
    # write the code for feature scaling here
    # Your code here
    # Calculate the mean and standard deviation for each column
    x_mean = x_train.mean(axis=0)
    x_std = x_train.std(axis=0)

    # Calculate the z-score for each value in the DataFrame
    x_train = (x_train - x_mean) / x_std
    # ---------

    return x_train,x_std,x_mean

In [19]:
def cost(x_train, y_train, w, b):

    # ---------
    # Your code here
    # Use mean square error as cost function
    # return cost
    # Number of training examples
  m = x_train.shape[0]

    # Compute the predictions
  predictions = np.dot(x_train, w) + b

    # Compute the squared differences

    # Compute the mean of the squared differences
  loss = np.mean((predictions - y_train) ** 2)

  return loss
  # ---------



In [20]:
def gradient_descent(x_train,y_train,w,b,learning_rate=0.01 , num_iterations=1):

  # ---------
    # Your code here
    # Choose learning rate yourself
    m = x_train.shape[0]

    for i in range(num_iterations):
        # Compute predictions
        predictions = np.dot(x_train, w) + b

        # Compute errors
        errors = predictions - y_train

        # Compute gradients
        dw = (1/m) * np.dot(x_train.T, errors)
        db = (1/m) * np.sum(errors)

        # Update parameters
        w -= learning_rate * dw
        b -= learning_rate * db
  # ---------

    return w,b

In [21]:
x_train = x_train.astype(np.float64)
x_train,x_std,x_mean = z_score(x_train)

np.random.seed(2147483647)
w = np.random.randn(x_train.shape[1],1)
b = np.random.randn(1)

# count = 0
old_cost = 0

while abs(old_cost - cost(x_train,y_train,w,b))>0.00001:
  old_cost = cost(x_train,y_train,w,b)
  w,b = gradient_descent(x_train,y_train,w,b)
  # count +=1
  #print(old_cost)

x_predict = pd.read_excel('Test data.xlsx').iloc[:,:8].to_numpy()
x_predict = feature_changing(x_predict)
x_predict = (x_predict - x_mean)/x_std
ans = pd.read_excel('Test data.xlsx').iloc[:,8].to_numpy()

y_predict = np.dot(x_predict,w) + b

accuracy = 0
for dim in range(len(ans)):
  if abs(y_predict[dim]-ans[dim])<0.5: # do not change the tolerance as you'll be checked on +- 0.5 error only
    accuracy += 1
accuracy = round(accuracy*100/200.0,2)
ok = 'Congratulations' if accuracy>95 else 'Optimization required'
print(f"{ok}, your accuracy is {accuracy}%")

Congratulations, your accuracy is 100.0%
